spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local_db
    username: root
    password: ssafy
    hikari:
      pool-name: hikari-pool
      maximum-pool-size: 5
      minimum-idle: 5
      connection-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 30000
      auto-commit: true
      read-only: false

mybatis:
  type-aliases-package: com.ssafy.notificationservice.*.infrastructure.repository.entity
  mapper-locations: mapper/**/*.xml

logging:
  level:
    jdbc:
      audit: DEBUG  # JDBC 커넥션 및 쿼리 실행 관련 로그
      resultset: DEBUG  # 쿼리 결과 로그
      sqlonly: DEBUG  # SQL 쿼리만 로깅
      sqltiming: DEBUG  # SQL 쿼리와 실행 시간 로깅
    org.mybatis: DEBUG  # MyBatis 관련 디버그 로그
    com.ssafy.notificationservice.repository: DEBUG  # repository 관련 디버그 로그
    com:
      zaxxer:
        hikari: INFO  # HikariCP 관련 로그 (DB 커넥션 풀)
