spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local_db
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikari-pool
      maximum-pool-size: 5
      minimum-idle: 5
      connection-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true

mybatis:
  type-aliases-package: com.ssafy.notificationservice.service.domain
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

firebase:
  config:
    path: firebase-adminsdk.json

logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO  # SQL 결과 데이터 테이블 로그
      sqlonly: OFF
      sqltiming: INFO  # SQL 및 소요 시간 로그
      connection: OFF
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
