spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S11P22A605?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S11P22A605@stg-yswa-kr-practice-db-master.mariadb.database.azure.com
    password: moremore
    hikari:
      pool-name: hikari-pool
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 30000
      auto-commit: true
      read-only: false


mybatis:
  type-aliases-package: com.ssafy.accountservice.account.infrastructure.repository.entity
  #  mapper-locations: mapper/**/.xml
  mapper-locations: classpath:mapper/*.xml

  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: DEBUG
    com.ssafy.accountservice.schedule.infrastructure.repository: DEBUG
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO  #SQL 결과 데이터 Table을 로그로 남긴다.
      sqlonly: OFF     #SQL만 로그로 남긴다.
      sqltiming: INFO    #SQL과 소요시간을 표기한다.
      connection : OFF  # 커넥션 확인가능
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

ssafy:
  account:
    number: "0016458849793120"
  api:
    key: "41ab6a7e28bf4af7b799e70ef9441967"
  user:
    key: "1bd1f427-19bb-40d0-bd3f-684133996793"
