spring:
  cloud:
    config:
      name: aws-common,db-common,logging-common,ssafyapi-common
  config:
    import: "optional:configserver:http://config-server.config"

aws:
  club-image:
    prefix: account/


mybatis:
  type-aliases-package: com.ssafy.accountservice.account.infrastructure.repository.entity

